# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/ToucPad_App/TouchPad_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RoboPharmacist_API(object):
    def setupUi(self, RoboPharmacist_API):
        RoboPharmacist_API.setObjectName("RoboPharmacist_API")
        RoboPharmacist_API.resize(1900, 554)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RoboPharmacist_API.sizePolicy().hasHeightForWidth())
        RoboPharmacist_API.setSizePolicy(sizePolicy)
        RoboPharmacist_API.setMinimumSize(QtCore.QSize(1700, 550))
        RoboPharmacist_API.setMaximumSize(QtCore.QSize(1900, 600))
        RoboPharmacist_API.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("green_cross_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RoboPharmacist_API.setWindowIcon(icon)
        RoboPharmacist_API.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(RoboPharmacist_API)
        self.gridLayout.setObjectName("gridLayout")
        self.label_SlowSpeed = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_SlowSpeed.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_SlowSpeed.setFont(font)
        self.label_SlowSpeed.setObjectName("label_SlowSpeed")
        self.gridLayout.addWidget(self.label_SlowSpeed, 7, 1, 1, 1)
        self.lineEdit_ID = QtWidgets.QLineEdit(RoboPharmacist_API)
        self.lineEdit_ID.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_ID.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        self.lineEdit_ID.setFont(font)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.gridLayout.addWidget(self.lineEdit_ID, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_3.setMinimumSize(QtCore.QSize(400, 80))
        self.label_3.setMaximumSize(QtCore.QSize(450, 80))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Robo_Pharmacist_logo_2_nobcg (2).png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 14, 1, 1, 3)
        self.Slider_Sensitivity = QtWidgets.QSlider(RoboPharmacist_API)
        self.Slider_Sensitivity.setMaximum(10)
        self.Slider_Sensitivity.setPageStep(1)
        self.Slider_Sensitivity.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Sensitivity.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_Sensitivity.setObjectName("Slider_Sensitivity")
        self.gridLayout.addWidget(self.Slider_Sensitivity, 8, 3, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 9, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(RoboPharmacist_API)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 12, 1, 1, 13)
        self.pushButton_STOP = QtWidgets.QPushButton(RoboPharmacist_API)
        self.pushButton_STOP.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_STOP.setFont(font)
        self.pushButton_STOP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_STOP.setAutoFillBackground(False)
        self.pushButton_STOP.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.pushButton_STOP.setAutoDefault(False)
        self.pushButton_STOP.setDefault(False)
        self.pushButton_STOP.setFlat(False)
        self.pushButton_STOP.setObjectName("pushButton_STOP")
        self.gridLayout.addWidget(self.pushButton_STOP, 14, 11, 1, 1)
        self.pushButton_RUN = QtWidgets.QPushButton(RoboPharmacist_API)
        self.pushButton_RUN.setMinimumSize(QtCore.QSize(0, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_RUN.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RUN.setFont(font)
        self.pushButton_RUN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_RUN.setAutoFillBackground(False)
        self.pushButton_RUN.setStyleSheet("background-color: rgb(0, 170, 0)")
        self.pushButton_RUN.setAutoDefault(False)
        self.pushButton_RUN.setDefault(False)
        self.pushButton_RUN.setFlat(False)
        self.pushButton_RUN.setObjectName("pushButton_RUN")
        self.gridLayout.addWidget(self.pushButton_RUN, 14, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 7, 1, 1)
        self.label_Number = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Number.setFont(font)
        self.label_Number.setObjectName("label_Number")
        self.gridLayout.addWidget(self.label_Number, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(RoboPharmacist_API)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 7, 1, 1)
        self.label_ID_hint = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_ID_hint.setFont(font)
        self.label_ID_hint.setObjectName("label_ID_hint")
        self.gridLayout.addWidget(self.label_ID_hint, 2, 5, 1, 1)
        self.label_SlowParticles = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_SlowParticles.setFont(font)
        self.label_SlowParticles.setObjectName("label_SlowParticles")
        self.gridLayout.addWidget(self.label_SlowParticles, 5, 1, 1, 1)
        self.label_Timer = QtWidgets.QLabel(RoboPharmacist_API)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_Timer.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Timer.setFont(font)
        self.label_Timer.setStyleSheet("background-color: white")
        self.label_Timer.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Timer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Timer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Timer.setObjectName("label_Timer")
        self.gridLayout.addWidget(self.label_Timer, 8, 11, 1, 1)
        self.label_CapsCounter = QtWidgets.QLabel(RoboPharmacist_API)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_CapsCounter.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_CapsCounter.setFont(font)
        self.label_CapsCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CapsCounter.setObjectName("label_CapsCounter")
        self.gridLayout.addWidget(self.label_CapsCounter, 2, 11, 1, 1)
        self.label_9 = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 5, 1, 1)
        self.label_Speed = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_Speed.setMinimumSize(QtCore.QSize(0, 50))
        self.label_Speed.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Speed.setFont(font)
        self.label_Speed.setObjectName("label_Speed")
        self.gridLayout.addWidget(self.label_Speed, 6, 1, 1, 1)
        self.lcdNumber_Parts = QtWidgets.QLCDNumber(RoboPharmacist_API)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.lcdNumber_Parts.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Parts.setSizePolicy(sizePolicy)
        self.lcdNumber_Parts.setMinimumSize(QtCore.QSize(0, 50))
        self.lcdNumber_Parts.setMaximumSize(QtCore.QSize(16777215, 5000))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.lcdNumber_Parts.setPalette(palette)
        self.lcdNumber_Parts.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcdNumber_Parts.setAutoFillBackground(False)
        self.lcdNumber_Parts.setStyleSheet("background-color: white\n"
"")
        self.lcdNumber_Parts.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_Parts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_Parts.setSmallDecimalPoint(True)
        self.lcdNumber_Parts.setObjectName("lcdNumber_Parts")
        self.gridLayout.addWidget(self.lcdNumber_Parts, 3, 7, 4, 1)
        self.lineEdit_SlowParticles = QtWidgets.QLineEdit(RoboPharmacist_API)
        self.lineEdit_SlowParticles.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_SlowParticles.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        self.lineEdit_SlowParticles.setFont(font)
        self.lineEdit_SlowParticles.setObjectName("lineEdit_SlowParticles")
        self.gridLayout.addWidget(self.lineEdit_SlowParticles, 5, 3, 1, 1)
        self.Slider_SlowSpeed = QtWidgets.QSlider(RoboPharmacist_API)
        self.Slider_SlowSpeed.setMaximumSize(QtCore.QSize(203, 16777215))
        self.Slider_SlowSpeed.setMaximum(3)
        self.Slider_SlowSpeed.setPageStep(1)
        self.Slider_SlowSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_SlowSpeed.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_SlowSpeed.setObjectName("Slider_SlowSpeed")
        self.gridLayout.addWidget(self.Slider_SlowSpeed, 7, 3, 1, 1)
        self.label_Sensitivity = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_Sensitivity.setMinimumSize(QtCore.QSize(0, 50))
        self.label_Sensitivity.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Sensitivity.setFont(font)
        self.label_Sensitivity.setObjectName("label_Sensitivity")
        self.gridLayout.addWidget(self.label_Sensitivity, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 5, 1, 1)
        self.lcdNumber_Caps = QtWidgets.QLCDNumber(RoboPharmacist_API)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Caps.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Caps.setSizePolicy(sizePolicy)
        self.lcdNumber_Caps.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lcdNumber_Caps.setPalette(palette)
        self.lcdNumber_Caps.setStyleSheet("background-color: white\n"
"")
        self.lcdNumber_Caps.setSmallDecimalPoint(True)
        self.lcdNumber_Caps.setObjectName("lcdNumber_Caps")
        self.gridLayout.addWidget(self.lcdNumber_Caps, 3, 11, 4, 1)
        self.lineEdit_CapsNumber = QtWidgets.QLineEdit(RoboPharmacist_API)
        self.lineEdit_CapsNumber.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_CapsNumber.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        self.lineEdit_CapsNumber.setFont(font)
        self.lineEdit_CapsNumber.setObjectName("lineEdit_CapsNumber")
        self.gridLayout.addWidget(self.lineEdit_CapsNumber, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(RoboPharmacist_API)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("background-color: white\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 7, 11, 1, 1)
        self.pushButton_MANUAL = QtWidgets.QPushButton(RoboPharmacist_API)
        self.pushButton_MANUAL.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_MANUAL.setFont(font)
        self.pushButton_MANUAL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_MANUAL.setObjectName("pushButton_MANUAL")
        self.gridLayout.addWidget(self.pushButton_MANUAL, 14, 5, 1, 1)
        self.label_CapsNumber = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_CapsNumber.setMinimumSize(QtCore.QSize(207, 50))
        self.label_CapsNumber.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_CapsNumber.setFont(font)
        self.label_CapsNumber.setStyleSheet("")
        self.label_CapsNumber.setObjectName("label_CapsNumber")
        self.gridLayout.addWidget(self.label_CapsNumber, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 5, 1, 1)
        self.Slider_Speed = QtWidgets.QSlider(RoboPharmacist_API)
        self.Slider_Speed.setStyleSheet("color: white")
        self.Slider_Speed.setMaximum(10)
        self.Slider_Speed.setPageStep(1)
        self.Slider_Speed.setProperty("value", 0)
        self.Slider_Speed.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Speed.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Slider_Speed.setObjectName("Slider_Speed")
        self.gridLayout.addWidget(self.Slider_Speed, 6, 3, 1, 3)
        self.label_ID = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_ID.setFont(font)
        self.label_ID.setObjectName("label_ID")
        self.gridLayout.addWidget(self.label_ID, 2, 1, 1, 1)
        self.lineEdit_Number = QtWidgets.QLineEdit(RoboPharmacist_API)
        self.lineEdit_Number.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_Number.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        self.lineEdit_Number.setFont(font)
        self.lineEdit_Number.setObjectName("lineEdit_Number")
        self.gridLayout.addWidget(self.lineEdit_Number, 4, 3, 1, 1)
        self.label_ParsCounter = QtWidgets.QLabel(RoboPharmacist_API)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_ParsCounter.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_ParsCounter.setFont(font)
        self.label_ParsCounter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_ParsCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ParsCounter.setObjectName("label_ParsCounter")
        self.gridLayout.addWidget(self.label_ParsCounter, 2, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_10.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 7, 13, 1, 1)
        self.label_7 = QtWidgets.QLabel(RoboPharmacist_API)
        self.label_7.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(RoboPharmacist_API)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 4, 1, 1)

        self.retranslateUi(RoboPharmacist_API)
        QtCore.QMetaObject.connectSlotsByName(RoboPharmacist_API)
        RoboPharmacist_API.setTabOrder(self.lineEdit_ID, self.lineEdit_CapsNumber)
        RoboPharmacist_API.setTabOrder(self.lineEdit_CapsNumber, self.lineEdit_Number)
        RoboPharmacist_API.setTabOrder(self.lineEdit_Number, self.lineEdit_SlowParticles)
        RoboPharmacist_API.setTabOrder(self.lineEdit_SlowParticles, self.Slider_Speed)
        RoboPharmacist_API.setTabOrder(self.Slider_Speed, self.Slider_SlowSpeed)
        RoboPharmacist_API.setTabOrder(self.Slider_SlowSpeed, self.Slider_Sensitivity)
        RoboPharmacist_API.setTabOrder(self.Slider_Sensitivity, self.pushButton_MANUAL)
        RoboPharmacist_API.setTabOrder(self.pushButton_MANUAL, self.pushButton_RUN)
        RoboPharmacist_API.setTabOrder(self.pushButton_RUN, self.pushButton_STOP)

    def retranslateUi(self, RoboPharmacist_API):
        _translate = QtCore.QCoreApplication.translate
        RoboPharmacist_API.setWindowTitle(_translate("RoboPharmacist_API", "RoboPharmacist"))
        self.label_SlowSpeed.setText(_translate("RoboPharmacist_API", " Slow Speed:"))
        self.pushButton_STOP.setText(_translate("RoboPharmacist_API", "STOP"))
        self.pushButton_RUN.setText(_translate("RoboPharmacist_API", "RUN"))
        self.label_2.setText(_translate("RoboPharmacist_API", "Dispensing Progress:"))
        self.label_Number.setText(_translate("RoboPharmacist_API", " Number of Parts:"))
        self.label_5.setText(_translate("RoboPharmacist_API", "Timer:"))
        self.label_ID_hint.setText(_translate("RoboPharmacist_API", "Define product-specific code"))
        self.label_SlowParticles.setText(_translate("RoboPharmacist_API", " Slow Parts:"))
        self.label_Timer.setText(_translate("RoboPharmacist_API", "00:00:00"))
        self.label_CapsCounter.setText(_translate("RoboPharmacist_API", "CAPSULE COUNTER"))
        self.label_9.setText(_translate("RoboPharmacist_API", "Number of particles in each capsule"))
        self.label_Speed.setText(_translate("RoboPharmacist_API", " Speed:"))
        self.label_Sensitivity.setText(_translate("RoboPharmacist_API", " Sensitivity:"))
        self.label.setText(_translate("RoboPharmacist_API", "Number of last particles dispensed with slow-speed"))
        self.label_13.setText(_translate("RoboPharmacist_API", "10"))
        self.label_8.setText(_translate("RoboPharmacist_API", "0"))
        self.pushButton_MANUAL.setText(_translate("RoboPharmacist_API", "Gantry Manual"))
        self.label_CapsNumber.setText(_translate("RoboPharmacist_API", " Number of Caps:"))
        self.label_4.setText(_translate("RoboPharmacist_API", "Number of capsules to be filled"))
        self.label_ID.setText(_translate("RoboPharmacist_API", " Product ID:"))
        self.label_ParsCounter.setText(_translate("RoboPharmacist_API", "PARTS COUNTER"))
        self.label_12.setText(_translate("RoboPharmacist_API", "10"))
        self.label_10.setText(_translate("RoboPharmacist_API", "0"))
        self.label_7.setText(_translate("RoboPharmacist_API", "0"))
        self.label_11.setText(_translate("RoboPharmacist_API", "3"))

